### ISSUE TITLE
Feature request: optional debug logs

### ISSUE THREAD

**Issue by photogenic89** [paylike/plugin-woocommerce#106]
Hi there,
would be great if writing debug logs could be optional in the future. Maybe just a simple checkbox input in the payment gateway options.
I'm using the WP debug logs to monitor php errors and Paylike writes transaction information in them which I do not need to know about. 
Kind regards
Jan

**Comment by ionutcalara** [comment]
Hi @photogenic89 at some point it was possible to disable the logs, but it might not be possible now in WooCommerce, I will double-check and get back to you next week. If there's no option, we'll build one and make that available.

**Comment by photogenic89** [comment]
Hi @ionutcalara . Have you had time to check this?

**Comment by ionutcalara** [comment]
Hi @photogenic89 yes, we will release an update on Monday that will allow you to disable the logs. I will update the issue here on that Is ready.

**Comment by ionutcalara** [comment]
@photogenic89 I have just released the 3.3.3 version here on github in case you are ok with using the zip directly. https://github.com/paylike/plugin-woocommerce/releases/download/v3.3.3/payment-gateway-via-paylike-for-woocommerce.3.3.3.zip

The wp.org version will be updated on Monday. The logs will be automatically disabled, in case you want to enable you can do that by adding this variable in your wp-config file and set it value to true. WP_ENABLE_PAYLIKE_LOGGING

I am closing this issue, but please reopen if you still have questions.
