### ISSUE TITLE
some translations missing

### ISSUE THREAD

**Issue by nagygabor** [paylike/plugin-woocommerce#46]
Hi,

2 strings are missing from woocommerce text domain, should move to woocommerce-gateway-paylike text domain

settings-paylike.php
- line 106: __( 'Accepted Cards', 'woocommerce' )
- line 110: __( 'Select the card types to accept.', 'woocommerce' ),

should add woocommerce-gateway-paylike text domain to
settings-paylike.php
__( 'Instant' )
__( 'Delayed' )

thanks,
Gabor

**Comment by ionutcalara** [comment]
This has been fixed here: https://github.com/paylike/plugin-woocommerce/pull/47

Thanks for letting me know 👍
