### ISSUE TITLE
paylike translate problem

### ISSUE THREAD

**Issue by petisbea** [paylike/plugin-woocommerce#71]
this sentence is in english instead of hungarian language on my website but the paylike plugin is translated to hunarian language so it could be in hungarian not in english. Can you help me please what do I have to do? How can I attache picture to this message?
![Untitled-2](https://user-images.githubusercontent.com/68548010/87941362-5602ff00-ca9b-11ea-8b40-ea1734e450b3.jpg)

**Comment by ionutcalara** [comment]
Hi @petisbea you can just drag the image that you want to into the text field. Please add it and I will have a look.

**Comment by petisbea** [comment]
My website built in wordpress / woocommerce / paylike plugin

**Comment by ionutcalara** [comment]
The latest version of the plugin should contain the translation. If the website is in Hungarian is should work. 
If updating the plugin doesn't work, you can create a new file in your theme/child-theme -> `paylike/receipt.php`. Inside you can add this: 

```
<p><?php
	echo __( 'Thank you for your order, please click below to pay and complete your order.', 'woocommerce-gateway-paylike' );
	?>
</p>
<button id="paylike-payment-button">
	<?php _e( 'Pay Now', 'woocommerce-gateway-paylike' ); ?>
</button>
```
and change the wording as you please. You can even remove it if you want to, what's important is to keep the button with the same id for the payment. Everything else can be changed. 

I will close this ticket, but let me know if you have further issues and I will reopen it.

**Comment by petisbea** [comment]
ok thank you
