### ISSUE TITLE
Woo Subscriptions/Memberships recurring payments failing

### ISSUE THREAD

**Issue by norbertpapp** [paylike/plugin-woocommerce#72]
Dear Support/Dev Team,

our client has a WordPress/WooCommerce based e-commerce site with Paylike payments set up using WooCommerce Memberships and Subscriptions plugins. Our client would like to use recurring payments in order to sell monthly paid membership services.

The memberships' initial payments and any other normal products payments are successful, but when a recurring payment is started we get the following error message in the order notes:
```
Paylike Transaction Failed (Neither Transaction ID nor Card ID was found)
```
I have checked the available docs and descriptions about the recurring payments at Paylike, haven't found any leads regarding this error message.

Is it possible due the used Paylike account does not have privileges to start recurring payments?
If you need more information about the shop or the hosting, please let me know.

**Comment by ionutcalara** [comment]
Hi @norbertpapp the error could have multiple causes. The woocommerce paylike plugin supports the woocommerce subscription plugin. However, the paylike account used for payments needs to be approved for recurring payments. You need to raise a support ticket for that. Please check that the client is approved for recurring payments. 

I will close the ticket for now but feel free to open if the issue persists and the recurring option is activated by the paylike team.
