### ISSUE TITLE
Paylike wrong payment finishing

### ISSUE THREAD

**Issue by isudjisu** [paylike/plugin-woocommerce#75]
Hello,
I would like to ask your help.
When we testing the payment method after the last step when accepted the payment the plugin dropped us to a 404 site.
https://www.raktaar.hu/order-received/82804/?key=wc_order_fsHVKKEgKCiXE
Where would be the problem?
thanx in advance

**Comment by ionutcalara** [comment]
Hi @isudjisu, it looks like the order received page was removed. Can you please create a page with the URL of order-received? If you edit the order received URL, you should change the slug under WooCommerce > Settings > Advanced.

Let me know if this helps.

**Comment by ionutcalara** [comment]
This issue was resolved, the problem was related to caching, and the script was being lazy loaded. A fix was implemented for the litespeed caching plugin to prevent the plugin from lazy loading the gateway script.
