### ISSUE TITLE
Error after API keys set

### ISSUE THREAD

**Issue by st91384** [paylike/plugin-woocommerce#83]
Hi,
I get an error message, when try to set the API keys:

"The live private key doesn't seem to be valid
Error: Network issues ! Check your connection and try again.
null"

Checked several times, the keys are correct, copy-pasted from the admin dashboard.

What can be the problem?

**Comment by ionutcalara** [comment]
Hi, @st91384 can you make sure that you followed this screenshot when adding the keys?
https://paylike.io/img/plugin-steps/fashion-outlet-paylike-create-account.jpg

**Comment by ionutcalara** [comment]
Also, in case the first step is correct, to debug curl, you will need to add the following under /plugins/payment-gateway-via-paylike-for-woocommerce/vendor/paylike/php-api/src/HttpClient/CurlClient.php at line 192. 
```
print_r(array('errorNo'=>$errno,'message'=>$message,'url'=>$url));
die();
```
After adding this, try again to validate the keys, and let me know what message you get. Comment these lines after testing.

**Comment by ionutcalara** [comment]
Hi there, due to the lack of response, I am closing this issue. Feel free to reopen.
