### ISSUE TITLE
error in the deducted order amounts

### ISSUE THREAD

**Issue by herszabi** [paylike/plugin-woocommerce#88]
Our webshop had issues with 2 transactions. Even though the total order amounts were 35,8 and 37,8 paylike deducted 34,8 from the customer's credit card.

**Comment by ionutcalara** [comment]
Hi @herszabi  sorry to hear that. Can you please send me the link of the website and products and a screenshot of that cart? Were you able to replicate the issue?

**Comment by herszabi** [comment]
Hi All,

This is the website: https://shopisland.bg/

Here are the screenshot of the orders:

[image: image.png]
[image: image.png]
They both ordered this product:
https://shopisland.bg/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%B8/cat-fish/

Best,
Szabina


Ionut Calara <notifications@github.com> ezt írta (időpont: 2021. márc. 4.,
Cs, 14:30):

**Comment by ionutcalara** [comment]
Hi @herszabi I am not able to see the images, but I was able to figure out the issue, you seem to have a donation plugin. Can you let me know what plugin is that? It doesn't seem to properly trigger an amount update. I will check to see if this is an error with our plugin, but this looks like that support plugin needs to trigger a proper checkout update.

**Comment by ionutcalara** [comment]
I am closing this for now, but feel free to reopen.
