### ISSUE TITLE
Checkout problem

### ISSUE THREAD

**Issue by bankav** [paylike/plugin-woocommerce#92]
Dear Paylike!

I'm having a problem because the Paylike payment option on my website disappears from Checkout for some reason. I made a video of exactly what was going on. When the page is loaded, the Credit Card payment option appears dimmed, then disappears when it is fully loaded. The same is true with other templates.

https://drive.google.com/file/d/15k4BRUzUn9NXgRDINnXcO3GIzcOfKVKA/view?usp=sharing

Can you help me with what I set up wrong?

Best regards,
Viktor Banka

**Comment by ionutcalara** [comment]
Hi @bankav are you using a custom checkout plugin?

**Comment by bankav** [comment]
Used to "Checkout for woo", but i uninstalled. Now i use the woocommerce
checkout in a layout of Cartzilla Theme.

Ionut Calara ***@***.***> ezt írta (időpont: 2021. ápr. 16.,
P, 10:55):

**Comment by ionutcalara** [comment]
Hi @bankav please reach out via paylike.io/contact so you can provide access for further debugging. I am afraid I can't tell what's wrong just from the video.

**Comment by ionutcalara** [comment]
Hi @bankav I am closing this, as I haven't heard back from you. Feel free to reach out as mentioned above so we can get this sorted.
