### ISSUE TITLE
Error message woocommerce.

### ISSUE THREAD

**Issue by Attila998** [paylike/plugin-woocommerce#93]
Hi!
I get this error message when I switch an order from processed to completed in woocommerce:
The request is not valid! Check if there is any validation bellow this message and adjust if possible, if not, and the problem persists, contact the developer.
Validation:
amount:Can capture at most HUF 0
![hibaüzenet](https://user-images.githubu
![hibaüzenet](https://user-images.githubusercontent.com/83224212/116086817-81f18780-a6a0-11eb-8fd4-5220ad1c84e8.PNG)
sercontent.com/83224212/116086770-730ad500-a6a0-11eb-8eef-1a9a9d6aa89c.PNG)

**Comment by ionutcalara** [comment]
Hi Attilla, this looks like the order was already captured. Check the paylike dashboard and see if the transaction was already captured there.

**Comment by ionutcalara** [comment]
Hi there, I am closing this ticket, but feel free to reopen if you still have questions.
