### ISSUE TITLE
Paylike error

### ISSUE THREAD

**Issue by luidzsi007** [paylike/plugin-woocommerce#96]
Dear Paylike!
There is a problem that when you come to the checkout page, you can select the credit card payment option, then clicking the send order button will not bring up the payment panel, or even navigate to a page not found, and I don't know what it is ...?! I attach the picture that is instead of the payment window, everything has been fine so far, so I don't even know what the problem is ...?
Although the card details would be entered, but it doesn't come in, it comes in instead, this is the no results page ...?
Thanks! Have a nice day!

**Comment by ionutcalara** [comment]
Hi @luidzsi007 can you try to disable all plugins but the paylike and woocommerce plugin? Let me know if you still have this issue.

**Comment by luidzsi007** [comment]
Hello.ionutcalara!  I turned off extensions and found the problematic extension. Cartflows is, just a pretty important plugin, so far it has been up to 2 plugins. I don't know how they got together? I want to use both, can it be solved somehow? Before that, the two extensions were used together ...

**Comment by ionutcalara** [comment]
Hi @luidzsi007, we can look into this matter if you reach out via our support channel and we get access to clone your website and try to see if there's something we can do to avoid the issue. However the timing is a bit off, I am going on vacation for 2 weeks, so the solution is probably something I could provide when I get back. In the meantime, I would try going through their support, it's more likely that this is an issue they can easily solve and would keep the plugin bug-free for you during their updates too. 

I am closing this ticket, but if you do not get anything from them, please get back to us via our support at hello@paylike.io. You can reference this ticket in the email.
