### ISSUE TITLE
Suggestion - Generic way to send payments to different accounts based on the currency

### ISSUE THREAD

**Issue by daigo75** [paylike/plugin-woocommerce#98]
I'm the author of [the Aelia Currency Switcher](https://aelia.co/shop/currency-switcher-woocommerce/) and I was asked by a common customer if it would be possible to adapt [the example from your documentation](https://github.com/paylike/plugin-woocommerce#change-account-keys-based-on-currency) to work with our solution. Based on my understanding, it should be simple enough. 

The code can be adapted to work with the Aelia Currency Switcher as follows:

Paylike - Change account keys based on the active currency
--
~~~
/**
 * Sets the private key depending on the active currency set by the Aelia Currency Switcher.
 *
 * @param string $default_secret_key
 * @return string
 */
add_filter('paylike_secret_key', function($default_secret_key) {
	$secret_keys = [
		'RON' => 'ron-secret-key',
		'EUR' => 'eur-secret-key',
		'GBP' => 'gbp-secret-key',
	];

	// Fetch the active  using the WooCommerce core function get_woocommerce_currency().
	// When the Aelia Currency Switcher is active, this will return the active currency 
	// automatically. When it's disabled, or absent, it will return the shop's base currency. 
	// No need to check for the presence of classes, functions, or call them directly.
	//
	// After that, return the secret key matching the active currency. If absent, return the 
	// default secret key
	return $secret_keys[get_woocommerce_currency()] ?? $default_secret_key;
});

/**
 * Sets the public key depending on the active currency set by the Aelia Currency Switcher.
 *
 * @param string $default_public_key
 * @return string
 */
add_filter('paylike_public_key', function($default_public_key) {
	$public_keys = [
		'RON' => 'ron-public-key',
		'EUR' => 'eur-public-key',
		'GBP' => 'gbp-public-key',
	];

	// Fetch the active  using the WooCommerce core function get_woocommerce_currency().
	// When the Aelia Currency Switcher is active, this will return the active currency 
	// automatically. When it's disabled, or absent, it will return the shop's base currency. 
	// No need to check for the presence of classes, functions, or call them directly.
	//
	// After that, return the public key matching the active currency. If absent, return the 
	// default public key
	return $public_keys[get_woocommerce_currency()] ?? $default_public_key;
});
~~~

This might also work with other multi-currency plugins, as long as they return the active currency when one calls `get_woocommerce_currency()`. I thought it would be a good idea to let you know, as that will increase cross-compatibility between plugins. 🙂

**Comment by ionutcalara** [comment]
I am closing this for now, but this should be available as a way for users to connect with your plugin. Let me know if you find that users need more than this, and we would consider a pull request, for a dedicated readme file.

**Comment by daigo75** [comment]
@ionutcalara The customers who tried the sample code said that it works fine. It could be a good idea to add a simple link to the example in the README file, so that users can see it right away.
